### ISSUE TITLE
Schema teams

### ISSUE THREAD

**Issue by arferreira** [zaptech-dev/rooster#9]

**Comment by yinho999** [comment]
Here are some logics which I found that could make sense, please let me know if any case missing.

1. Team Management:
- Create, update, and delete teams. (Owner/Admin within team)
- List all teams a user is part of. (All users in the team)
- Add and remove members from a team. (Admin within team)

2. Role Management:
- Define roles within teams. (Owner/Admin within team)
- Assign roles to team members. (Owner/Admin within team)
- Update or remove roles from team members. (Owner/Admin within team)

3. Invitation System:
- Send invitations to users to join a team. (Owner/Admin within team, or Team Lead)
- Accept or decline invitations. (Does not require any special permissions, but should be able to accept or deny)
- Track whether an invitation has been claimed. (Owner/Admin within team, or Team Lead to view and manage the state of the team's membership)

4. Subscription Management:
- Subscribe a team to a service. (Owner/Admin within team)
- Update subscription details. (Owner/Admin within team)
- Cancel subscriptions. (Owner/Admin within team)
